module.exports = {
  "ARG": "Argentina",
  "ARM": "Armenia",
  "AT": "Austria",
  "AUS": "Australia",
  "BE": "Belgium",
  "BEN": "Benin",
  "BFA": "Burkina Faso",
  "BG": "Bulgaria",
  "BOL": "Bolivia",
  "BRA": "Brazil",
  "CHI": "China",
  "CHL": "Chile",
  "CH": "Switzerland",
  "CIV": "Ivory Coast",
  "COL": "Colombia",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DK": "Denmark",
  "ECU": "Ecuador",
  "EE": "Estonia",
  "EL": "Greece",
  "ES": "Spain",
  "FI": "Finland",
  "FR": "France",
  "GAM": "Gambia",
  "GEO": "Georgia",
  "GHA": "Ghana",
  "GNB": "Guinea-Bissau",
  "GTM": "Guatemala",
  "HR": "Croatia",
  "HU": "Hungary",
  "IDN": "Indonesia",
  "IE": "Ireland",
  "IND": "India",
  "IS": "Iceland",
  "IT": "Italy",
  "KAZ": "Kazakhstan",
  "KGZ": "Kyrgyzstan",
  "KOR": "South Korea",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "MEX": "Mexico",
  "MLI": "Mali",
  "MNG": "Mongolia",
  "MT": "Malta",
  "MWI": "Malawi",
  "NER": "Niger",
  "NGA": "Nigeria",
  "NL": "Netherlands",
  "NO": "Norway",
  "NPL": "Nepal",
  "PAN": "Panama",
  "PER": "Peru",
  "PL": "Poland",
  "PT": "Portugal",
  "RO": "Romania",
  "SEN": "Senegal",
  "SE": "Sweden",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "SRL": "Sierra Leone",
  "TGO": "Togo",
  "TJK": "Tajikistan",
  "TIM": "Timor-Leste",
  "TZN": "Tanzania",
  "UGA": "Uganda",
  "UK": "United Kingdom",
  "USA": "United States",
  "UZB": "Uzbekistan",
  "ZAF": "South Africa"
};
